package com.example.seller.route

enum class Routes {
    SPLASH_SCREEN,
    ON_BOARDING,
    REGISTRATION_PHONE,
    REGISTRATION_PIN_CODE,
    REGISTRATION_CRE_PIN_CODE,
    AUTHORIZATION,
    BASE_SCREEN,
    PROFILE_INFORMATION
}